const bookList = [
    { title: "Harry Potter and the Philosopher's Stone", slug: 'harry-potter-and-the-philosophers-stone', author: "JK Rowling", publish_year: 1997, synopsis: "A story about about a boy named Harry Potter and a Philospher's Stone. ", image: 'https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg' },
    { title: "Harry Potter and the Chamber of Secrets", slug: 'harry-potter-and-the-chamber-of-secrets', author: "JK Rowling", publish_year: 1998, synopsis:"A story about about a boy named Harry Potter and the Chamber of Secrets.", image: 'https://upload.wikimedia.org/wikipedia/en/5/5c/Harry_Potter_and_the_Chamber_of_Secrets.jpg' },
    { title: "Harry Potter and the Prisoner of Azkaban", slug: 'harry-potter-and-the-prisoner-of-azkaban', author: "JK Rowling", publish_year: 1999, synopsis:"A story about about a boy named Harry Potter and the Prisoner of Azkaban.", image: 'https://upload.wikimedia.org/wikipedia/en/a/a0/Harry_Potter_and_the_Prisoner_of_Azkaban.jpg' },
    { title: "Harry Potter and the Goblet of Fire", slug: 'harry-potter-and-the-goblet-of-fire', author: "JK Rowling", publish_year: 2000, synopsis:"A story about about a boy named Harry Potter and the Goblet of Fire.", image: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Harry_Potter_and_the_Goblet_of_Fire_cover.png' },
    { title: "Harry Potter and the Order of the Phoenix", slug: 'harry-potter-and-the-order-of-the-phoenix', author: "JK Rowling", publish_year: 2003, synopsis: "A story about about a boy named Harry Potter and  Order of the Phoenix.", image: 'https://upload.wikimedia.org/wikipedia/en/7/70/Harry_Potter_and_the_Order_of_the_Phoenix.jpg' },
    { title: "Harry Potter and the Half-Blood Prince", slug: 'harry-potter-and-the-half-blood-prince', author: "JK Rowling", publish_year: 2005, synopsis:"A story about about a boy named Harry Potter and the Half-blood Prince.", image: 'https://upload.wikimedia.org/wikipedia/en/b/b5/Harry_Potter_and_the_Half-Blood_Prince_cover.png' },
    { title: "Harry Potter and the Deathly Hallows", slug: 'harry-potter-and-the-deathly-hallows', author: "JK Rowling", publish_year: 2007, synopsis: "A story about about a boy named Harry Potter and the Deathly Hallows.", image: 'https://upload.wikimedia.org/wikipedia/en/a/a9/Harry_Potter_and_the_Deathly_Hallows.jpg' },
  ]
  
  module.exports = bookList